name: Deploy iSEE subdomains

on:
  workflow_dispatch:
  push:
    branches:
      - devel
    paths:
      - 'config.csv'

concurrency:
  group: deploy-isee-subdomains
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v4

      - name: save kubeconfig
        shell: bash
        run: mkdir -p ~/.kube && echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
      
      - name: Install Kubectl
        run: |
          curl -LO "https://storage.googleapis.com/kubernetes-release/release/v1.24.4/bin/linux/amd64/kubectl" && \
          chmod +x ./kubectl && \
          mv ./kubectl /usr/local/bin/kubectl && \
          kubectl version

      - name: Clean up old pods
        run: |
          kubectl get pod -n isee-cofest2025 -o name | xargs -i kubectl delete -n isee-cofest2025 {}

      - name: Deploy iSEE subdomains
        shell: bash
        run: |
          python3 .github/scripts/parse_csv.py config.csv | awk -F'#@#' '{
            ORIGID = $1
            datasetURI = $2 
            configURI = $3
            
            # Convert ID to lowercase
            ID = tolower(ORIGID)
            
            printf "Deploying %s with dataset %s and config %s\n", ID, datasetURI, configURI
            
            APP_FILE = "app-" ID ".R"
            YAML_FILE = "deployment-" ID ".yaml"
            
            # Generate app.R file
            cmd = "sed -e \"s|##PLACEHOLDERDATASETURI##|\\\"" datasetURI "\\\"|g\" -e \"s|##PLACEHOLDERCONFIGURI##|\\\"" configURI "\\\"|g\" .github/templates/app.R > " APP_FILE
            system(cmd)
            
            # Generate deployment YAML
            cmd = "sed -e \"s/##PLACEHOLDERID##/" ID "/g\" .github/templates/isee-deployment.yaml > " YAML_FILE
            system(cmd)
            
            # Create namespace
            printf "Creating namespace %s-isee...\n", ID
            cmd = "kubectl create namespace " ID "-isee"
            system(cmd)
            
            # Create configmap
            printf "Creating configmap %s-isee-app...\n", ID
            cmd = "kubectl create configmap " ID "-isee-app --from-file=app.R=" APP_FILE " --namespace=" ID "-isee"
            system(cmd)
            
            # Apply deployment
            printf "Applying deployment YAML...\n"
            cmd = "kubectl apply -f " YAML_FILE " --namespace=" ID "-isee"
            system(cmd)
            
            # Clean up
            cmd = "rm -f " APP_FILE " " YAML_FILE
            system(cmd)
            
            printf "Successfully deployed %s.isee.bioconductor.org\n", ID
            print "---"
          }
          END {
            print "All deployments completed!"
          }'
